name: Scan Container Images
on:
  push:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prisma Cloud Container Image Scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        with:
          pcc_console_url: https://asia-south1.cloud.twistlock.com/india-1131963775
          pcc_user: f4326d9a-b2fe-4aff-91b5-9b36d620e9dd
          pcc_pass: g6Q5pXRYhBtnVotl7ApukKvN/80=
          image_name: docker.io/library/nginx
          #container_tag: latest
      - name: Upload JSON File         
        uses: actions/upload-artifact@v2        
        with:           
          name: results           
          path: ${{ github.workspace }}/pcc_scan_results.sarif.json  
        if: always()
          
      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/pcc_scan_results.sarif.json
